parameters:
    linkvalue.mobilenotif.client.client_collection: LinkValue\MobileNotifBundle\Client\ClientCollection

services:
    linkvalue.mobilenotif.clients:
        class: %linkvalue.mobilenotif.client.client_collection%
